{
 "title": "Climate",
 "tags": [ "tesla" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "vehicle_name",
    "query": "select distinct(display_name) from (select * from charge_state)"
   }
  ]
 },
 "panels": [
  {
   "title": "FAN Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "fan_status",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "climate_state",
     "select": [
      [
       { "params": [ "fan_status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    },
    {
     "alias": "inside_temp",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "climate_state",
     "select": [
      [
       { "params": [ "inside_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    },
    {
     "alias": "outside_temp",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "climate_state",
     "select": [
      [
       { "params": [ "outside_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Seat Heater :: Left",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "climate_state",
     "query": "SELECT \"value\" FROM \"climate_state\" WHERE (\"metric\" = 'seat_heater_right' AND \"display_name\" =~ /^$vehicle_name$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "seat_heater_left" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Steering Wheel",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "measurement": "climate_state",
     "query": "SELECT last(\"steering_wheel_heater\") FROM \"climate_state\" WHERE (\"display_name\" =~ /^$vehicle_name$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "steering_wheel_heater" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Seat Heater :: Right",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "climate_state",
     "query": "SELECT \"value\" FROM \"climate_state\" WHERE (\"metric\" = 'seat_heater_right' AND \"display_name\" =~ /^$vehicle_name$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "seat_heater_right" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Seat Heater :: Rear Left",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "climate_state",
     "query": "SELECT \"value\" FROM \"climate_state\" WHERE (\"metric\" = 'seat_heater_right' AND \"display_name\" =~ /^$vehicle_name$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "seat_heater_rear_left" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Seat Heater :: Rear Center",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "climate_state",
     "query": "SELECT \"value\" FROM \"climate_state\" WHERE (\"metric\" = 'seat_heater_right' AND \"display_name\" =~ /^$vehicle_name$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "seat_heater_rear_center" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Seat Heater :: Rear Right",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "climate_state",
     "query": "SELECT \"value\" FROM \"climate_state\" WHERE (\"metric\" = 'seat_heater_right' AND \"display_name\" =~ /^$vehicle_name$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "seat_heater_rear_right" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  }
 ]
}